management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 9090
  servlet:
    context-path: /library-server

library:
  user-srv: ${USER_SERVICE_URI}
  inventory-srv: ${INVENTORY_SERVICE_URI}
  borrow-srv: ${BORROW_SERVICE_URI}
  server:
    keycloak:
      serverUrl: ${KEYCLOAK_SERVER_URI}
      realmId: ${KEYCLOAK_REALM_ID}

# Properties provided by com.example.library.users.properties.SwaggerProperties
swagger:
  keycloak:
    clientId: ${SWAGGER_CLIENT_ID}
    clientSecret: ${SWAGGER_CLIENT_SECRET}
  api-info:
    title: "OIDC Sample: Library Server"
    description: "This service provides a facade that cascades the borrow and the inventory services."
    version: "1.0.0"
    termsOfServiceUrl: "http://www.baloise.ch/terms-of-service"
    license: "Apache 2.0"
    licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
    contact:
      name: "John Doe"
      url: "http://www.baloise.ch"
      email: "john.doe@baloise.ch"
