management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID}
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: none
            scope: openid
        provider:
          keycloak:
            issuerUri: ${ISSUER_URI}
            user-name-attribute: name

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 9090
  servlet:
    context-path: /library-server

library:
  user-srv: ${USER_SERVICE_URI}
  inventory-srv: ${INVENTORY_SERVICE_URI}
  borrow-srv: ${BORROW_SERVICE_URI}
