management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/workshop
      client:
        registration:
          keycloak:
            clientId: library-client
            authorizationGrantType: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            client-authentication-method: none
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:8080/auth/realms/workshop
            user-name-attribute: name

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 9090
  servlet:
    context-path: /library-server

library:
  user-srv: http://localhost:9093/library-users
  inventory-srv: http://localhost:9092/library-inventory
  borrow-srv: http://localhost:9091/library-borrow
  server:
    keycloak:
      serverUrl: http://localhost:8080/auth
      realmId: workshop

# Properties provided by com.example.library.users.properties.SwaggerProperties
swagger:
  keycloak:
    clientId: library-client
    clientSecret: 9584640c-3804-4dcd-997b-93593cfb9ea7
  api-info:
    title: "OIDC Sample: Library Server"
    description: "This service provides a facade that cascades the borrow and the inventory services."
    version: "1.0.0"
    termsOfServiceUrl: "http://www.baloise.ch/terms-of-service"
    license: "Apache 2.0"
    licenseUrl: "https://www.apache.org/licenses/LICENSE-2.0"
    contact:
      name: "John Doe"
      url: "http://www.baloise.ch"
      email: "john.doe@baloise.ch"
