management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/workshop/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/workshop

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 9093
  servlet:
    context-path: /library-users

library:
  server:
    keycloak:
      serverUrl: http://localhost:8080/auth
      realmId: workshop
      clientId: keycloak-admin
      clientSecret: ab14c208-a2ee-47a9-9fd5-04c93cc61a2a
