management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    open-in-view: false
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI}
          issuer-uri: ${ISSUER_URI}

logging:
  level:
    org:
      springframework:
        security: debug
server:
  error:
    include-stacktrace: never
  port: 9093
  servlet:
    context-path: /library-users

library:
  server:
    keycloak:
      serverUrl: ${KEYCLOAK_SERVER_URI}
      realmId: ${KEYCLOAK_REALM_ID}
      clientId: ${CLIENT_ID}
      clientSecret: ${KEYCLOAK_CLIENT_SECRET}
